#ifndef ANALYTICAL_WRAPPING_ANALYTICALSOLUTION_H
#define ANALYTICAL_WRAPPING_ANALYTICALSOLUTION_H

double analyticalSolution(double leftHeight, const testCase& aCase);

#endif //ANALYTICAL_WRAPPING_ANALYTICALSOLUTION_H
